### ISSUE TITLE
Updating user information breaks the app

### ISSUE THREAD

**Issue by fdnklg** [freestyle-players-association/fpa-app#36]
Updating user information on the profile page breaks the app.

```
 ⨯ validation-schemas/user-profile-schema.ts (6:17) @ File
 ⨯ ReferenceError: File is not defined
    at eval (./validation-schemas/user-profile-schema.ts:9:59)
    at (action-browser)/./validation-schemas/user-profile-schema.ts (/Users/enjoi/projects/fpa-app/.next/server/app/[locale]/user-profile/update/page.js:809:1)
    at __webpack_require__ (/Users/enjoi/projects/fpa-app/.next/server/webpack-runtime.js:33:43)
    at eval (./next-server-functions/user-profile/update-user-profile-action.ts:8:97)
    at (action-browser)/./next-server-functions/user-profile/update-user-profile-action.ts (/Users/enjoi/projects/fpa-app/.next/server/app/[locale]/user-profile/update/page.js:721:1)
    at Function.__webpack_require__ (/Users/enjoi/projects/fpa-app/.next/server/webpack-runtime.js:33:43)
digest: "1548959236"
  4 |   username: z.string().min(3, "Too short"),
  5 |   avatar: z
> 6 |     .instanceof(File)
    |                 ^
  7 |     .refine((file) => file.type.includes("image"), "Must be of type image")
  8 |     .refine((file) => file.size < 1024 * 1024, "File must be 1Mb or smaller"),
  9 | });
```

**Comment by zzZCodeZzz** [comment]
Could not reproduce as aang and as newly created test user.
Could you document how I reproduce this?
Maybe I'm just dumb here

**Comment by fdnklg** [comment]
1. Log in as `Uppa`
2. add a last name and hit `Update user profile`

This will cause an infinite loop locally on my end with the above mentioned error message.

**Comment by gaddoz** [comment]
hey all, new guy here, looking into some issues for getting started on contributing here.
I was not able to replicate the issue as well, but I thought it would be nice to start adding some tests.
So #43 is adding cypress and the user journey.
Let me know if you like adding cypress, if we should open a topic and discuss about it.
